// Angular/Test_Angular_Project1/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Route, Router } from '@angular/router';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {

  constructor(public router:Router) { }

  ngOnInit(): void {
  }

}



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <h2 style="color: blue; font-size: 30px;font-style: italic;">AngularProject Demo</h2>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li>
            <a routerLink="/" routerLinkActive="active">Home</a>
          </li>
        <li class="nav-item">
          <a routerLink="/course" routerLinkActive="active">Courses</a>
        </li>

        <li class="nav-item" style="padding-left: 500px;">
          <a routerLink="/login" routerLinkActive="active">Login</a>
        </li>
        <li class="nav-item" >
          <a routerLink="/register" routerLinkActive="active">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

// reactApp/react_with_jango/frontend/src/components/layout/Header.js
import React, { Component } from 'react'

export class Header extends Component {
    render() {
        return (
            <div>
                <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <a className="navbar-brand" href="#">Navbar</a>
                <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav">
                    <li className="nav-item active">
                        <a className="nav-link" href="#">Home <span className="sr-only">(current)</span></a>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link" href="#">Features</a>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link" href="#">Pricing</a>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link disabled" href="#">Disabled</a>
                    </li>
                </ul>
            </div>
            </nav>
                            
         </div>
        )
    }
}

export default Header
